// QA Test Character Generator
// Run with: dart run test_character_generator.dart


void main() {
  print('Generating 15 QA test characters...\n');
  
  final characters = [
    createCharacter1_USRangerSOF(),
    createCharacter2_UKOfficerEOD(),
    createCharacter3_GermanJTAC(),
    createCharacter4_FrenchSOFAgent(),
    createCharacter5_CanadianBasic(),
    createCharacter6_AustralianMultiSchool(),
    createCharacter7_USWoundedVeteran(),
    createCharacter8_PolishOfficer(),
    createCharacter9_ItalianSergeant(),
    createCharacter10_JapaneseMinimal(),
    createCharacter11_SpanishMaxAttributes(),
    createCharacter12_DutchRangerNoSOF(),
    createCharacter13_SwedishMultiDeployment(),
    createCharacter14_BelgianBreacher(),
    createCharacter15_NorwegianEdgeCases(),
  ];
  
  print('\n✅ Generated ${characters.length} test characters');
  print('\nTest Coverage:');
  print('- Ranger → SOF progression with promotion');
  print('- Officer paths with EOD and canine companion');
  print('- JTAC specialty with different nationalities');
  print('- Full progression: Ranger → SOF → Agent');
  print('- Baseline soldier (no special paths)');
  print('- Multiple schools variety');
  print('- Purple Heart and awards system');
  print('- Officer and sergeant promotions');
  print('- Minimal selections edge case');
  print('- Maximum attribute allocation');
  print('- Ranger without joining SOF');
  print('- Multiple deployments');
  print('- Skill stacking (Breacher + Explosives)');
  print('- Text field edge cases (long strings, special chars)');
  
  print('\n📝 Copy and paste these into your Firebase console or use manual creation in the app.');
  print('Character IDs to test: ${characters.map((c) => c['name']).join(', ')}');
}

Map<String, dynamic> createCharacter1_USRangerSOF() {
  return {
    'id': 'qa-test-1-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Jake "Havoc" Morrison',
    'nickname': 'Havoc',
    'age': 28,
    'homeLocation': 'Fort Benning, GA',
    'nationality': 'United States',
    'height': 72,
    'weight': 185,
    'languages': ['English'],
    'motivation': 'Prove himself worthy of Ranger tab',
    'background': 'Infantry',
    'trademark': 'Worn Ranger tab patch on shoulder',
    'specialtyHook': 'First in team to breach doors',
    'characterHook': '',
    'isSOF': true,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 8,
      'Agility': 7,
      'Combat Wisdom': 6,
      'Combat Knowledge': 8,
    },
    'skills': {
      'Small Arms': 4,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 2,
      'Combat': 2,
      'Training': 2,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Staff Sergeant (E-6)',
      'specialty': 'SOF Infantry',
      'narrative': 'Jake "Havoc" Morrison, age 28 from Fort Benning, GA, is a SOF Infantry soldier...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 6},
      'baseSkills': {'Small Arms': 3, 'Heavy Weapons': 1, 'First Aid': 1},
      'deployments': [
        {
          'location': 'Afghanistan',
          'year': '2019',
          'school': 'Ranger (Knowledge +1)',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Syria',
          'year': '2021',
          'school': 'Airborne',
          'award': 'Bronze Star (+2 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
      'sofSchool': 'Breacher (Explosives +2)',
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter2_UKOfficerEOD() {
  return {
    'id': 'qa-test-2-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Oliver Blackwood',
    'nickname': 'Bomber',
    'age': 32,
    'homeLocation': 'London',
    'nationality': 'United Kingdom',
    'height': 70,
    'weight': 175,
    'languages': ['English'],
    'motivation': 'Defuse the impossible',
    'background': 'Engineering',
    'trademark': 'Always carries lucky coin',
    'specialtyHook': 'Talks to his dog during defusal',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': 'Belgian Malinois',
    'canineName': 'Rex',
    'attributes': {
      'Strength': 6,
      'Agility': 7,
      'Combat Wisdom': 8,
      'Combat Knowledge': 7,
    },
    'skills': {
      'Small Arms': 2,
      'Heavy Weapons': 1,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 1,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 8,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Officer',
      'rank': 'Captain (O-3)',
      'specialty': 'EOD',
      'narrative': 'Oliver "Bomber" Blackwood, age 32 from London, is an EOD specialist...',
      'baseAttributes': {'Strength': 5, 'Agility': 6, 'Combat Wisdom': 7, 'Combat Knowledge': 5},
      'baseSkills': {'First Aid': 2, 'Radio Ops': 1},
      'deployments': [
        {
          'location': 'Iraq',
          'year': '2020',
          'school': 'Small Boats',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
          'promotionRank': 'Captain (O-3)',
        },
        {
          'location': 'Afghanistan',
          'year': '2022',
          'school': 'Air Assault',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
          'newSpecialty': 'EOD',
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter3_GermanJTAC() {
  return {
    'id': 'qa-test-3-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Klaus Schmidt',
    'nickname': '',
    'age': 26,
    'homeLocation': 'Berlin',
    'nationality': 'Germany',
    'height': 73,
    'weight': 190,
    'languages': ['German', 'English'],
    'motivation': 'Call in precision strikes',
    'background': 'Communications',
    'trademark': 'Red headset',
    'specialtyHook': 'Never misses a radio check',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 6,
      'Agility': 5,
      'Combat Wisdom': 7,
      'Combat Knowledge': 6,
    },
    'skills': {
      'Small Arms': 2,
      'Heavy Weapons': 1,
      'First Aid': 1,
      'Radio Ops': 5,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 6,
      'Signals Intel': 1,
      'Explosives': 0,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'JTAC',
      'narrative': 'Klaus Schmidt, age 26 from Berlin, is a JTAC specialist...',
      'baseAttributes': {'Strength': 6, 'Agility': 5, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Radio Ops': 3, 'Signals Intel': 1},
      'deployments': [
        {
          'location': 'Kosovo',
          'year': '2021',
          'school': 'Airborne',
          'award': 'None',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Mali',
          'year': '2023',
          'school': 'Breacher (Explosives +2)',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
          'newSpecialty': 'JTAC',
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter4_FrenchSOFAgent() {
  return {
    'id': 'qa-test-4-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Pierre Dubois',
    'nickname': 'Ghost',
    'age': 34,
    'homeLocation': 'Paris',
    'nationality': 'France',
    'height': 69,
    'weight': 170,
    'languages': ['French', 'English', 'Arabic'],
    'motivation': 'Infiltrate enemy networks',
    'background': 'Intelligence',
    'trademark': 'False passport collection',
    'specialtyHook': 'Knows every extraction route',
    'characterHook': '',
    'isSOF': true,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 7,
      'Agility': 8,
      'Combat Wisdom': 9,
      'Combat Knowledge': 8,
    },
    'skills': {
      'Small Arms': 4,
      'Heavy Weapons': 1,
      'First Aid': 2,
      'Radio Ops': 2,
      'Civil Affairs': 2,
      'Spying': 6,
      'Fires': 0,
      'Signals Intel': 1,
      'Explosives': 0,
      'Combat': 2,
      'Training': 3,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant First Class (E-7)',
      'specialty': 'Agent',
      'narrative': 'Pierre "Ghost" Dubois, age 34 from Paris, is an Agent...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Spying': 2, 'Civil Affairs': 1},
      'deployments': [
        {
          'location': 'Chad',
          'year': '2018',
          'school': 'Ranger (Knowledge +1)',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Syria',
          'year': '2020',
          'school': 'Small Boats',
          'award': 'Silver Star (+3 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
      'sofSchool': 'Hostage Rescue (Small Arms +1)',
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter5_CanadianBasic() {
  return {
    'id': 'qa-test-5-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Connor MacLeod',
    'nickname': '',
    'age': 23,
    'homeLocation': 'Toronto',
    'nationality': 'Canada',
    'height': 71,
    'weight': 180,
    'languages': ['English', 'French'],
    'motivation': 'Serve my country',
    'background': 'Infantry',
    'trademark': 'Maple leaf tattoo',
    'specialtyHook': '',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 6,
      'Agility': 6,
      'Combat Wisdom': 5,
      'Combat Knowledge': 5,
    },
    'skills': {
      'Small Arms': 3,
      'Heavy Weapons': 2,
      'First Aid': 1,
      'Radio Ops': 0,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 1,
      'Training': 0,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Private (E-1)',
      'specialty': 'Infantry',
      'narrative': 'Connor MacLeod, age 23 from Toronto, is an Infantry soldier...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 5, 'Combat Knowledge': 5},
      'baseSkills': {'Small Arms': 3, 'Heavy Weapons': 1},
      'deployments': [
        {
          'location': 'Latvia',
          'year': '2024',
          'school': 'Air Assault',
          'award': 'None',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

// Continue with remaining 10 characters...
Map<String, dynamic> createCharacter6_AustralianMultiSchool() {
  return {
    'id': 'qa-test-6-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Jack Harrison',
    'nickname': 'Croc',
    'age': 29,
    'homeLocation': 'Sydney',
    'nationality': 'Australia',
    'height': 72,
    'weight': 188,
    'languages': ['English'],
    'motivation': 'Master every skill',
    'background': 'Recon',
    'trademark': 'Boonie hat',
    'specialtyHook': 'Always finds water source',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 8,
      'Agility': 7,
      'Combat Wisdom': 6,
      'Combat Knowledge': 6,
    },
    'skills': {
      'Small Arms': 3,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 1,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 2,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Infantry',
      'narrative': 'Jack "Croc" Harrison, age 29 from Sydney...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Small Arms': 2, 'First Aid': 1},
      'deployments': [
        {
          'location': 'East Timor',
          'year': '2020',
          'school': 'Small Boats',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Afghanistan',
          'year': '2022',
          'school': 'Airborne',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter7_USWoundedVeteran() {
  return {
    'id': 'qa-test-7-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Marcus "Steel" Rodriguez',
    'nickname': 'Steel',
    'age': 35,
    'homeLocation': 'San Antonio, TX',
    'nationality': 'United States',
    'height': 70,
    'weight': 175,
    'languages': ['English', 'Spanish'],
    'motivation': 'Honor fallen brothers',
    'background': 'Infantry',
    'trademark': 'Purple Heart pin',
    'specialtyHook': 'Never leaves anyone behind',
    'characterHook': '',
    'isSOF': false,
    'medals': ['Purple Heart', 'Bronze Star'],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 7,
      'Agility': 6,
      'Combat Wisdom': 9,
      'Combat Knowledge': 10,
    },
    'skills': {
      'Small Arms': 5,
      'Heavy Weapons': 3,
      'First Aid': 3,
      'Radio Ops': 2,
      'Civil Affairs': 1,
      'Spying': 0,
      'Fires': 1,
      'Signals Intel': 0,
      'Explosives': 1,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Infantry',
      'narrative': 'Marcus "Steel" Rodriguez, age 35 from San Antonio...',
      'baseAttributes': {'Strength': 7, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Small Arms': 4, 'Heavy Weapons': 2},
      'deployments': [
        {
          'location': 'Iraq',
          'year': '2018',
          'school': 'Air Assault',
          'award': 'Bronze Star (+2 Knowledge)',
          'survival': 'Wounded (Purple Heart)',
          'awards': ['Purple Heart'],
        },
        {
          'location': 'Syria',
          'year': '2021',
          'school': 'Breacher (Explosives +2)',
          'award': 'Silver Star (+3 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter8_PolishOfficer() {
  return {
    'id': 'qa-test-8-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Aleksander Kowalski',
    'nickname': 'Aleks',
    'age': 30,
    'homeLocation': 'Warsaw',
    'nationality': 'Poland',
    'height': 74,
    'weight': 195,
    'languages': ['Polish', 'English'],
    'motivation': 'Lead from the front',
    'background': 'Military Academy',
    'trademark': 'Family saber',
    'specialtyHook': 'Quotes Sun Tzu',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 8,
      'Agility': 7,
      'Combat Wisdom': 7,
      'Combat Knowledge': 8,
    },
    'skills': {
      'Small Arms': 3,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 2,
      'Civil Affairs': 1,
      'Spying': 0,
      'Fires': 1,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 1,
      'Training': 2,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Officer',
      'rank': 'Captain (O-3)',
      'specialty': 'Infantry',
      'narrative': 'Aleksander "Aleks" Kowalski, age 30 from Warsaw...',
      'baseAttributes': {'Strength': 5, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Radio Ops': 1, 'Civil Affairs': 1},
      'deployments': [
        {
          'location': 'Romania',
          'year': '2023',
          'school': 'Small Boats',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
          'promotionRank': 'Captain (O-3)',
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter9_ItalianSergeant() {
  return {
    'id': 'qa-test-9-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Giovanni Rossi',
    'nickname': 'Gio',
    'age': 27,
    'homeLocation': 'Rome',
    'nationality': 'Italy',
    'height': 69,
    'weight': 165,
    'languages': ['Italian', 'English'],
    'motivation': 'Support my squad',
    'background': 'Medic',
    'trademark': 'Lucky cross necklace',
    'specialtyHook': 'First to volunteer',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 5,
      'Agility': 6,
      'Combat Wisdom': 8,
      'Combat Knowledge': 6,
    },
    'skills': {
      'Small Arms': 2,
      'Heavy Weapons': 1,
      'First Aid': 5,
      'Radio Ops': 1,
      'Civil Affairs': 2,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 2,
      'Training': 2,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Staff Sergeant (E-6)',
      'specialty': 'Medic',
      'narrative': 'Giovanni "Gio" Rossi, age 27 from Rome...',
      'baseAttributes': {'Strength': 5, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'First Aid': 4, 'Civil Affairs': 1},
      'deployments': [
        {
          'location': 'Afghanistan',
          'year': '2021',
          'school': 'Air Assault',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Iraq',
          'year': '2023',
          'school': 'Airborne',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter10_JapaneseMinimal() {
  return {
    'id': 'qa-test-10-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Takeshi Yamamoto',
    'nickname': '',
    'age': 22,
    'homeLocation': 'Tokyo',
    'nationality': 'Japan',
    'height': 68,
    'weight': 160,
    'languages': ['Japanese'],
    'motivation': 'Duty',
    'background': 'Infantry',
    'trademark': '',
    'specialtyHook': '',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 5,
      'Agility': 5,
      'Combat Wisdom': 6,
      'Combat Knowledge': 6,
    },
    'skills': {
      'Small Arms': 2,
      'Heavy Weapons': 1,
      'First Aid': 0,
      'Radio Ops': 0,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 0,
      'Training': 0,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Private (E-1)',
      'specialty': 'Infantry',
      'narrative': 'Takeshi Yamamoto, age 22 from Tokyo...',
      'baseAttributes': {'Strength': 5, 'Agility': 5, 'Combat Wisdom': 6, 'Combat Knowledge': 6},
      'baseSkills': {'Small Arms': 2, 'Heavy Weapons': 1},
      'deployments': [],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter11_SpanishMaxAttributes() {
  return {
    'id': 'qa-test-11-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Carlos "Tank" Hernandez',
    'nickname': 'Tank',
    'age': 31,
    'homeLocation': 'Madrid',
    'nationality': 'Spain',
    'height': 75,
    'weight': 210,
    'languages': ['Spanish', 'English'],
    'motivation': 'Be the strongest',
    'background': 'Infantry',
    'trademark': 'Weightlifting belt',
    'specialtyHook': 'Carries heaviest gear',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 10,
      'Agility': 8,
      'Combat Wisdom': 7,
      'Combat Knowledge': 9,
    },
    'skills': {
      'Small Arms': 4,
      'Heavy Weapons': 5,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 1,
      'Signals Intel': 0,
      'Explosives': 2,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Heavy Weapons',
      'narrative': 'Carlos "Tank" Hernandez, age 31 from Madrid...',
      'baseAttributes': {'Strength': 8, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Heavy Weapons': 4, 'Small Arms': 2},
      'deployments': [
        {
          'location': 'Mali',
          'year': '2020',
          'school': 'Small Boats',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Afghanistan',
          'year': '2022',
          'school': 'Ranger (Knowledge +1)',
          'award': 'Bronze Star (+2 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter12_DutchRangerNoSOF() {
  return {
    'id': 'qa-test-12-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Willem "Wil" de Vries',
    'nickname': 'Wil',
    'age': 28,
    'homeLocation': 'Amsterdam',
    'nationality': 'Netherlands',
    'height': 73,
    'weight': 185,
    'languages': ['Dutch', 'English', 'German'],
    'motivation': 'Ranger is enough',
    'background': 'Infantry',
    'trademark': 'Orange armband',
    'specialtyHook': 'Prefers conventional warfare',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 7,
      'Agility': 7,
      'Combat Wisdom': 6,
      'Combat Knowledge': 8,
    },
    'skills': {
      'Small Arms': 4,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 1,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Infantry',
      'narrative': 'Willem "Wil" de Vries, age 28 from Amsterdam...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 6},
      'baseSkills': {'Small Arms': 3, 'Heavy Weapons': 1},
      'deployments': [
        {
          'location': 'Mali',
          'year': '2021',
          'school': 'Ranger (Knowledge +1)',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Afghanistan',
          'year': '2023',
          'school': 'Air Assault',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter13_SwedishMultiDeployment() {
  return {
    'id': 'qa-test-13-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Erik Andersson',
    'nickname': 'Viking',
    'age': 33,
    'homeLocation': 'Stockholm',
    'nationality': 'Sweden',
    'height': 72,
    'weight': 180,
    'languages': ['Swedish', 'English'],
    'motivation': 'See the world through war',
    'background': 'Infantry',
    'trademark': 'Thor\'s hammer pendant',
    'specialtyHook': 'Has deployment patch from every continent',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 7,
      'Agility': 6,
      'Combat Wisdom': 8,
      'Combat Knowledge': 7,
    },
    'skills': {
      'Small Arms': 4,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 2,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 0,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Infantry',
      'narrative': 'Erik "Viking" Andersson, age 33 from Stockholm...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 5},
      'baseSkills': {'Small Arms': 3, 'First Aid': 1},
      'deployments': [
        {
          'location': 'Afghanistan',
          'year': '2019',
          'school': 'Small Boats',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Mali',
          'year': '2021',
          'school': 'Airborne',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter14_BelgianBreacher() {
  return {
    'id': 'qa-test-14-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Luc "Boom" Mercier',
    'nickname': 'Boom',
    'age': 29,
    'homeLocation': 'Brussels',
    'nationality': 'Belgium',
    'height': 70,
    'weight': 175,
    'languages': ['French', 'Dutch', 'English'],
    'motivation': 'Master explosives',
    'background': 'Engineering',
    'trademark': 'Det cord bracelet',
    'specialtyHook': 'Calculates blast radius instantly',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 7,
      'Agility': 6,
      'Combat Wisdom': 7,
      'Combat Knowledge': 7,
    },
    'skills': {
      'Small Arms': 2,
      'Heavy Weapons': 1,
      'First Aid': 1,
      'Radio Ops': 1,
      'Civil Affairs': 0,
      'Spying': 0,
      'Fires': 0,
      'Signals Intel': 0,
      'Explosives': 6,
      'Combat': 2,
      'Training': 1,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Sergeant (E-5)',
      'specialty': 'Infantry',
      'narrative': 'Luc "Boom" Mercier, age 29 from Brussels...',
      'baseAttributes': {'Strength': 6, 'Agility': 6, 'Combat Wisdom': 6, 'Combat Knowledge': 6},
      'baseSkills': {'Explosives': 2},
      'deployments': [
        {
          'location': 'Afghanistan',
          'year': '2021',
          'school': 'Breacher (Explosives +2)',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
        {
          'location': 'Syria',
          'year': '2023',
          'school': 'Breacher (Explosives +2)',
          'award': 'Commendation (+1 Knowledge)',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}

Map<String, dynamic> createCharacter15_NorwegianEdgeCases() {
  return {
    'id': 'qa-test-15-${DateTime.now().millisecondsSinceEpoch}',
    'name': 'Bjørn "The-Mountain\'s-Shadow" Håkonsson-Vestergaard',
    'nickname': 'The-Mountain\'s-Shadow',
    'age': 99,
    'homeLocation': 'Tromsø, Arctic Norway, Land of the Midnight Sun',
    'nationality': 'Norway',
    'height': 84,
    'weight': 250,
    'languages': ['Norwegian', 'English', 'Russian', 'Finnish', 'Swedish', 'Danish', 'Icelandic'],
    'motivation': 'Test the limits of this character creation system with exceptionally long text strings and special characters: æøå!@#\$%^&*()_+-=[]{}|;:,.<>?',
    'background': 'Military Academy',
    'trademark': 'Carries ancient Viking axe blessed by modern-day Norse priest while wearing tactical gear covered in runes & symbols !@#\$%',
    'specialtyHook': 'Recites entire Poetic Edda from memory during night watch, can navigate by stars alone, master of cold weather survival techniques passed down through generations',
    'characterHook': '',
    'isSOF': false,
    'medals': [],
    'canineBreed': '',
    'canineName': '',
    'attributes': {
      'Strength': 10,
      'Agility': 10,
      'Combat Wisdom': 6,
      'Combat Knowledge': 6,
    },
    'skills': {
      'Small Arms': 3,
      'Heavy Weapons': 2,
      'First Aid': 2,
      'Radio Ops': 1,
      'Civil Affairs': 1,
      'Spying': 1,
      'Fires': 1,
      'Signals Intel': 1,
      'Explosives': 1,
      'Combat': 1,
      'Training': 0,
    },
    'enlistment': {
      'service': 'Army',
      'rankType': 'Enlisted',
      'rank': 'Private (E-1)',
      'specialty': 'Infantry',
      'narrative': 'Bjørn "The-Mountain\'s-Shadow" Håkonsson-Vestergaard, age 99 from Tromsø...',
      'baseAttributes': {'Strength': 10, 'Agility': 10, 'Combat Wisdom': 6, 'Combat Knowledge': 6},
      'baseSkills': {'Small Arms': 3, 'Heavy Weapons': 1},
      'deployments': [
        {
          'location': 'Svalbard (Edge of the World)',
          'year': '2024',
          'school': 'Air Assault',
          'award': 'Achievement',
          'survival': 'Survived unscathed',
          'awards': [],
        },
      ],
    },
    'inventory': {},
  };
}
