// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9A6CLqG0kL-msyIhyHBe9owh_mYEfbU',
    appId: '1:203732910394:web:18845c4fd695a97354d003',
    messagingSenderId: '203732910394',
    projectId: 'patrol-character-generator',
    authDomain: 'patrol-character-generator.firebaseapp.com',
    storageBucket: 'patrol-character-generator.firebasestorage.app',
    measurementId: 'G-06BEY6WFQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3tBiL-XgM14DcHfNdM6azTTRU5MrqC0',
    appId: '1:203732910394:android:87e89a9a6ba51b9754d003',
    messagingSenderId: '203732910394',
    projectId: 'patrol-character-generator',
    storageBucket: 'patrol-character-generator.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqr72b7nhV7zEcyBaKowmL1H0FqZRNfSc',
    appId: '1:203732910394:ios:24f132c868fe544f54d003',
    messagingSenderId: '203732910394',
    projectId: 'patrol-character-generator',
    storageBucket: 'patrol-character-generator.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4patrol',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqr72b7nhV7zEcyBaKowmL1H0FqZRNfSc',
    appId: '1:203732910394:ios:24f132c868fe544f54d003',
    messagingSenderId: '203732910394',
    projectId: 'patrol-character-generator',
    storageBucket: 'patrol-character-generator.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4patrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgULLmczCnXUDmygA1R1Pkx-2YTJv_Znk',
    appId: '1:203732910394:web:4ce7c92faef5c79c54d003',
    messagingSenderId: '203732910394',
    projectId: 'patrol-character-generator',
    authDomain: 'patrol-character-generator.firebaseapp.com',
    storageBucket: 'patrol-character-generator.firebasestorage.app',
    measurementId: 'G-MDR8TGBM9N',
  );
}
